---
app_title: Frozen Inventory System
location_singular: Truhe
location_plural: Truhen
location_emoji: "\U0001F3E2"
item_context: frozen
aging_enabled: true
aging_warning_days: 120
aging_danger_days: 180
aging_fresh_label: fresh
aging_warning_label: getting old
aging_danger_label: very old
