---
app_title: Noret Freezers
location_singular: Fridge
location_plural: Fridges
location_emoji: "\U0001F3E2"
item_context: frozen
aging_enabled: true
aging_warning_days: 120
aging_danger_days: 180
aging_fresh_label: fresh
aging_warning_label: getting old
aging_danger_label: very old
